In [1]:
import numpy as np

In [2]:
# 此代码演示了创建0维标量数组，打印数组并查看数组维度
arr=np.array(1)
print(arr)
print("arr的维度",arr.ndim)

1
arr的维度 0


In [3]:
# 此代码演示了创建一维数组，打印数组并查看数组维度
arr=np.array([1])
print(arr)
print("arr的维度",arr.ndim)

[1]
arr的维度 1


In [4]:
# 此代码演示了创建二维嵌套数组，打印数组并查看数组维度
arr=np.array([[1],[2]])
print(arr)
print("arr的维度",arr.ndim)

[[1]
 [2]]
arr的维度 2


In [5]:
# 此代码演示了数组混合数字与字符串元素，会自动整体转为字符串类型
arr=np.array([1,"w."])
print(arr)

['1' 'w.']


In [6]:
# 此代码演示了数组混合整数与浮点数，会自动整体统一为浮点类型
arr=np.array([1,1.5])
print(arr)

[1.  1.5]


In [7]:
# 此代码演示了查看0维标量数组的形状、维度、元素总数、转置结果
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的转置', arr.T)

1
数组的形状： ()
数组的维度： 0
元素的个数： 1
元素的转置 1


In [8]:
# 此代码演示了查看二维数组的形状、维度、元素总数、完成数组转置
arr = np.array([[1],[2]])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：', arr.ndim)
print('元素的个数：', arr.size)
print('元素的转置', arr.T)

[[1]
 [2]]
数组的形状： (2, 1)
数组的维度： 2
元素的个数： 2
元素的转置 [[1 2]]


In [9]:
# 此代码演示了Python原生列表转为NumPy数组，查看数组维度
list1 = [1]
arr = np.array(list1)
print(arr.ndim)
print(arr)

1
[1]


In [10]:
# 此代码演示了数组深拷贝，修改拷贝后的数组不会影响原数组
arr = np.array([1,2,3])
arr1 = np.copy(arr)
print(arr1)
arr1[0] = 2
print(arr1)
print(arr)

[1 2 3]
[2 2 3]
[1 2 3]


In [11]:
# 此代码演示了创建2行3列全0数组，并查看数组元素数据类型
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [12]:
# 此代码演示了创建长度为10、元素全为0的一维数组
arr = np.zeros((10,))
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
# 此代码演示了创建2行3列、元素全为1的二维数组
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# 此代码演示了创建2行3列、未初始化的空数组
arr = np.empty((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# 此代码演示了创建2行3列、所有元素都填充为750的数组
arr = np.full((2,3),750)
print(arr)

[[750 750 750]
 [750 750 750]]


In [16]:
# 此代码演示了基于已有数组形状，快速创建同规格全0、空、全1、全指定值数组
arr = np.full((2,3),750)
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.full_like(arr,750 )
print(arr1)

[[0 0 0]
 [0 0 0]]
[[1684930614 1281110881 1634886249]
 [1650227570 1144745577 1849777210]]
[[1 1 1]
 [1 1 1]]
[[750 750 750]
 [750 750 750]]


In [17]:
# 此代码演示了通过起始值、结束值、步长，生成一维等差数组
arr = np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [18]:
# 此代码演示了在指定区间内，生成指定数量的等间距均匀数组
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [19]:
# 此代码演示了以2为底，在对数刻度区间生成指定数量的等比数组
arr = np.logspace(1,10,5,base=2)
print(arr)

[   2.            9.51365692   45.254834    215.2694823  1024.        ]


In [20]:
# 此代码演示了创建2行3列的对角单位矩阵
arr = np.eye(2,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]]


In [21]:
# 此代码演示了根据指定对角线元素，生成对角方阵
arr = np.diag((1,2,3))
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [22]:
# 此代码演示了生成2行3列、0~1区间均匀分布的随机小数数组
arr = np.random.rand(2,3)
print(arr)

[[0.5669389  0.8223975  0.53385377]
 [0.51174251 0.71378699 0.09631727]]


In [23]:
# 此代码演示了生成2行3列、2~3区间均匀分布的随机浮点数数组
arr = np.random.uniform(2,3,(2,3))
print(arr)

[[2.11211614 2.23049605 2.89488508]
 [2.58914509 2.87807248 2.36553051]]


In [24]:
# 此代码演示了生成2行3列、1~10区间的随机整数二维数组
arr = np.random.randint(1,10,(2,3))
print(arr)

[[7 8 1]
 [2 7 2]]


In [25]:
# 此代码演示了生成2行3列、服从标准正态分布的随机数组
arr = np.random.randn(2,3)
print(arr)

[[ 0.81687492 -1.72941317 -2.08620219]
 [-2.1777824   0.86406743  0.94864971]]


In [26]:
# 此代码演示了设置随机种子，保证生成的随机数组结果可复现
np.random.seed(10)
arr = np.random.randint(1,10,(2,3))
print(arr)

[[5 1 2]
 [1 2 9]]


In [27]:
# 此代码演示了手动创建布尔bool类型的NumPy数组
arr = np.array([0,1], dtype= np.bool)
print(arr)

[False  True]


In [28]:
# 此代码演示了手动创建int8位整数类型的NumPy数组
arr = np.array([0,1], dtype= np.int8)
print(arr)

[0 1]


In [29]:
# 此代码演示了生成长度10、指定范围的一维随机整数数组
arr = np.random.randint(1,10,10)
print(arr)

[1 9 7 5 4 1 5 7 9 2]


In [30]:
# 此代码演示了一维数组下标索引、切片、布尔索引、slice对象索引取值
arr = np.random.randint(1,10,10)
print(arr[0])
print(arr[:])
print(arr[2:5])
print(arr[(arr>5) & (arr<10)])
print(arr[slice(2,5,2)])

9
[9 5 2 4 7 6 4 7 2 5]
[2 4 7]
[9 7 6 7]
[2 7]


In [31]:
# 此代码演示了生成2行3列二维随机整数数组
arr = np.random.randint(1,100,(2,3))
print(arr)

[[28 19 94]
 [78 23 24]]


In [32]:
# 此代码演示了二维数组行列索引、切片、条件索引精准取值
arr = np.random.randint(1,100,(2,3))
print(arr[1,1])
print(arr[1,1:5])
print(arr[1][arr[1] >50])
print(arr[:,2])

89
[89 10]
[75 89]
[29 10]


In [33]:
# 此代码演示了两个一维数组逐元素加、减、乘、除、平方幂运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [34]:
# 此代码演示了两个二维数组逐元素完整四则运算与幂运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[7,8,9],[4,5,6],[1,2,3]])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]
[[0.14285714 0.25       0.33333333]
 [1.         1.         1.        ]
 [7.         4.         3.        ]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [35]:
# 此代码演示了二维数组和标量直接广播加法、乘法
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a + 3)
print(a * 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [36]:
# 此代码演示了不同维度数组之间的广播减法运算
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a-b)

[[-3 -2 -1]
 [-4 -3 -2]
 [-5 -4 -3]]


In [37]:
# 此代码演示了两个同形状二维数组逐元素对应相乘
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[7,8,9],[4,5,6],[1,2,3]])
print(a * b)

[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]


In [38]:
# 此代码演示了对单个数值与数组批量计算平方根
print(np.sqrt(4))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

2.0
[1. 2. 3.]
[1. 5. 9.]


In [39]:
# 此代码演示了计算自然常数e的n次幂
print(np.exp(1))

2.718281828459045


In [40]:
# 此代码演示了计算数值的自然对数
print(np.log(2.71))

0.9969486348916096


In [41]:
# 此代码演示了三角函数正弦sin、余弦cos数值计算
print(np.sin(np.pi/2))
print(np.cos(np.pi/4))

1.0
0.7071067811865476


In [42]:
# 此代码演示了计算数组全部元素的绝对值
arr = np.array([-3,-1, 1, 2])
print(np.abs(arr))

[3 1 1 2]


In [43]:
# 此代码演示了对数组全部元素进行3次幂次方运算
arr = np.array([-3,-1, 1, 2])
print(np.power(arr,3))

[-27  -1   1   8]


In [44]:
# 此代码演示了对数组浮点数元素进行四舍五入取整
print(np.round([0.27, 5.89, 3.16]))

[0. 6. 3.]


In [45]:
# 此代码演示了对数组元素向上取整ceil、向下取整floor
arr = np.array([7.42, 1.08, 9.65])
print(np.ceil(arr))
print(np.floor(arr))

[ 8.  2. 10.]
[7. 1. 9.]


In [46]:
# 此代码演示了判断数组元素是否为NaN非空无效值
print(np.isnan([1, 2, 3]))

[False False False]


In [47]:
# 此代码演示了生成一维指定范围随机整数数组
arr = np.random.randint(1,100,10)
print(arr)

[16 19 81 72 89 12 18 47  8 76]


In [48]:
# 此代码演示了计算数组全部元素总和
arr = np.random.randint(1,100,10)
print(np.sum(arr))

551


In [49]:
# 此代码演示了计算数组全部元素平均值
arr = np.random.randint(1,100,10)
print(np.mean(arr))

52.2


In [50]:
# 此代码演示了计算数组全部元素中位数
arr = np.random.randint(1,100,10)
print(np.median(arr))

58.0


In [51]:
# 此代码演示了计算数组元素方差与标准差
arr = np.random.randint(1,100,10)
print(np.var(arr))
print(np.std(arr))

872.76
29.54251174155644


In [52]:
# 此代码演示了获取数组元素最大值、最小值
arr = np.random.randint(1,100,10)
print(np.max(arr))
print(np.min(arr))

85
4


In [53]:
# 此代码演示了计算数组的20%分位数值
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,20))

2.6


In [54]:
# 此代码演示了计算数组元素累计求和、累计求乘积
arr = np.array([1,2,3,4,5])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [55]:
# 此代码演示了数组逐元素大于、小于、相等的大小比较运算
print(np.greater([1,2,3,4,5],3))
print(np.less([1,2,3,4,5],3))
print(np.equal([1,2,3,4,5],3))
print(np.equal([1,2,3],[3,4,5]))

[False False False  True  True]
[ True  True False False False]
[False False  True False False]
[False False False]


In [56]:
# 此代码演示了数组逐元素与、或、非三种基础逻辑运算
print(np.logical_and([1,0],[1,1]))
print(np.logical_or([0,0],[1,0]))
print(np.logical_not([1,0]))

[ True False]
[ True False]
[False  True]


In [57]:
# 此代码演示了any判断是否存在真值、all判断是否全部为真值
print(np.any([0,0]))
print(np.all([1,1]))

False
True


In [58]:
# 此代码演示了np.where单条件判断，按需替换数组内元素
arr = np.array([1,2,3,4,5])
print(np.where(arr<3, arr, 0))
print(np.where(arr<3,1,0))

[1 2 0 0 0]
[1 1 0 0 0]


In [59]:
# 此代码演示了嵌套np.where，实现成绩多档位分段评级
score = np.random.randint(30,100,20)
print(score)
print(np.where(score>=60,'及格','不及格'))
print(np.where(
    score<60,'不及格',np.where(
    score<80,'良好','优秀'
)))

[83 55 78 47 62 71 42 60 47 46 30 61 94 68 52 96 97 92 57 92]
['及格' '不及格' '及格' '不及格' '及格' '及格' '不及格' '及格' '不及格' '不及格' '不及格' '及格' '及格'
 '及格' '不及格' '及格' '及格' '及格' '不及格' '及格']
['优秀' '不及格' '良好' '不及格' '良好' '良好' '不及格' '良好' '不及格' '不及格' '不及格' '良好' '优秀'
 '良好' '不及格' '优秀' '优秀' '优秀' '不及格' '优秀']


In [60]:
# 此代码演示了np.select多条件批量匹配映射结果
score = np.random.randint(30,100,20)
print(np.select([score>80,(score>=60) & (score<=80),score<60],['优秀','良好','不及格']))

['良好' '良好' '不及格' '不及格' '良好' '良好' '良好' '良好' '不及格' '不及格' '良好' '不及格' '优秀'
 '不及格' '良好' '良好' '不及格' '不及格' '良好' '不及格']


In [61]:
# 此代码演示了固定随机种子、生成指定范围随机整数数组、并对数组升序排序
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
print(np.sort(arr))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]


In [62]:
# 此代码演示了提取数组中不重复唯一值、以及横向拼接两个一维数组
arr = np.array([1,2,3,4,5,6])
print(np.unique(arr))
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [63]:
# 此代码演示了按照指定下标位置，将一维数组拆分为多个子数组
arr = np.random.randint(1,100,20)
print(np.split(arr,[6,12,18]))

[array([82, 38, 26, 78, 73, 10]), array([21, 81, 70, 80, 48, 65]), array([83, 89, 50, 30, 20, 20]), array([15, 40])]


In [64]:
# 此代码演示了将一维数组重塑为4行5列的二维数组
arr = np.random.randint(1,100,20)
print(np.reshape(arr,[4,5]))

[[33 66 10 58 33]
 [32 75 24 36 76]
 [56 29 35  1  1]
 [37 54  6 39 18]]
